"use client"
import { getChapterData, getCourseById, getChaptersByCourseId } from '@/configs/action';
import React, { use, useEffect, useState } from 'react'
import ChapterListCard from './_component/ChapterListCard';
import ChapterContent from './_component/ChapterContent';
import { HiOutlineDocumentDownload } from 'react-icons/hi';
import { HiOutlineTrophy, HiOutlineLockClosed } from 'react-icons/hi2';
import { useRouter } from 'next/navigation';

function CourseStart({ params }) {
    const unwrappedParams = use(params);
    const courseId = unwrappedParams?.courseId;
    const router = useRouter();

    const [courseInfo, setCourseInfo] = useState(null);
    const [loading, setLoading] = useState(true);
    const [selectedChapter, setSelectedChapter] = useState(null);
    const [chapterContent, setChapterContent] = useState();
    const [dbChapters, setDbChapters] = useState([]);

    useEffect(() => {
        const GetCourse = async () => {
            if (!courseId) return;
            setLoading(true);
            try {
                const res = await getCourseById(courseId);
                setCourseInfo(res);

                const chaptersRes = await getChaptersByCourseId(courseId);
                setDbChapters(chaptersRes);

                if (res?.courseOutput?.Chapters?.length > 0) {
                    setSelectedChapter(res.courseOutput.Chapters[0]);
                    GetSelectedChapterContent(0, chaptersRes);
                }
            } catch (error) {
                console.log('Unable to fetch the course: ', error);
            } finally {
                setLoading(false);
            }
        }

        GetCourse();
    }, [courseId]);

    const GetSelectedChapterContent = async (index, chapters = dbChapters) => {
        const content = chapters.find(c => c.chapterId == String(index));
        if (content) {
            setChapterContent(content);
        } else {
            console.error("Chapter content not found in local state");
        }
    }

    const downloadCourseAsMarkdown = () => {
        if (!courseInfo) return;
        {/* converting the course info into markdown */ }
        let markdown = `# ${courseInfo?.courseOutput?.["Course Name"]}\n\n`;
        markdown += `*Generated by Curriculum AI*\n\n---\n\n`;

        {/* iterating over the chapters and converting them into markdown */ }
        courseInfo?.courseOutput?.Chapters?.forEach((chapter, index) => {
            markdown += `## Chapter ${index + 1}: ${chapter?.["Chapter Name"]}\n\n`;
            markdown += `**Duration:** ${chapter?.Duration}\n\n`;
            markdown += `${chapter?.about}\n\n`;

            {/* the detailed explination and code example is taken from the dbChapter as it is not present in the courseInfo */ }
            const dbChapter = dbChapters.find(c => c.chapterId == String(index));
            if (dbChapter?.content?.description) {
                markdown += `### Detailed Explanation\n\n${dbChapter.content.description}\n\n`;
            }
            {/* checks if the codeExample exists and if it exist it uses a regex to strip out all html tags and at 
            last uses .trim to remove invisible space and new line */}
            if (dbChapter?.content?.codeExample && dbChapter.content.codeExample.replace(/<[^>]*>?/gm, '').trim() !== "") {
                markdown += `### Code Example\n\n${dbChapter.content.codeExample}\n\n`;
            }
            markdown += `---\n\n`;
        });

        {/* the markdown content is converted into blob because we can't download the markdown content directly */ }
        const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });

        {/* creates a temporary local URL that points directly to the file in memory */ }
        const url = URL.createObjectURL(blob);
        {/* creates an invisible anchor tag in the background */ }
        const a = document.createElement("a");
        a.href = url;
        {/* sets the download attribute with the file name and there is regex 
            that searches for spaces and replace it with '_' */}
        a.download = `${courseInfo?.courseOutput?.["Course Name"]?.replace(/\s+/g, '_') || 'Course'}.md`;
        document.body.appendChild(a);
        {/* it stimulates a human physically clicking the invisible link */ }
        a.click();
        {/* removing the link */ }
        document.body.removeChild(a);
        {/* revoking the url crucial for performance to prevent memory leak because thr text filw will be stored in RAm
            untill user closes the tab */}
        URL.revokeObjectURL(url);
    };

    return (
        <div className='flex min-h-screen bg-background'>

            {/* Sidebar */}
            <div className='md:w-72 hidden md:block h-screen fixed border-r border-border/50 bg-[#0d0d14] z-10'>
                <div className='p-4 border-b border-border/50'>

                    {/* display the title */}
                    <h2 className='font-semibold text-sm text-white leading-snug line-clamp-2'>
                        {courseInfo?.courseOutput?.["Course Name"]}
                    </h2>

                    {/* displaying the progress status and the percentage of course completed */}
                    <div className='flex items-center justify-between mt-3'>
                        {/* calculating the fraction of completed chapters */}
                        <p className='text-xs text-[#B3B3B3]'>
                            {/* we are filtering out the chapters from the output based on the indexes which are completed */}
                            {courseInfo?.courseOutput?.Chapters?.filter((_, idx) => dbChapters.find(c => c.chapterId == String(idx))?.completed).length || 0} / {courseInfo?.courseOutput?.Chapters?.length || 0} completed
                        </p>
                        {/* calculates the percentage of course completed */}
                        <p className='text-xs font-bold text-[#1DB954]'>
                            {courseInfo?.courseOutput?.Chapters?.length > 0 ? Math.round(((courseInfo?.courseOutput?.Chapters?.filter((_, idx) => dbChapters.find(c => c.chapterId == String(idx))?.completed).length || 0) / courseInfo?.courseOutput?.Chapters?.length) * 100) : 0}%
                        </p>
                    </div>

                    {/* Progress Bar */}
                    {/* we are filling the progress bar based on the percentage of the completed chapters which is calculated above */}
                    <div className="w-full bg-[#282828] rounded-full h-1.5 mt-2 overflow-hidden">
                        {/* the inner div has dynamic width which changes on the basis of chapters completed */}
                        <div
                            className="bg-[#1DB954] h-1.5 transition-all duration-500"
                            style={{ width: `${courseInfo?.courseOutput?.Chapters?.length > 0 ? ((courseInfo?.courseOutput?.Chapters?.filter((_, idx) => dbChapters.find(c => c.chapterId == String(idx))?.completed).length || 0) / courseInfo?.courseOutput?.Chapters?.length) * 100 : 0}%` }}
                        ></div>
                    </div>
                </div>

                {/* list of chapters */}
                <div className='overflow-y-auto h-[calc(100vh-240px)] custom-scrollbar'>
                    {courseInfo?.courseOutput?.Chapters.map((chapter, index) => (
                        <div
                            key={index}
                            className={`cursor-pointer transition-all duration-200 hover:bg-white/[0.03] ${selectedChapter?.["Chapter Name"] === chapter?.["Chapter Name"] && 'bg-[#1DB954]/10 border-l-2 border-[#1DB954]'}`}
                            onClick={() => {
                                setSelectedChapter(chapter);
                                GetSelectedChapterContent(index, dbChapters);
                            }}
                        >
                            <ChapterListCard
                                chapter={chapter}
                                index={index}
                                isCompleted={dbChapters.find(c => c.chapterId == String(index))?.completed}
                            />
                        </div>
                    ))}
                </div>

                {/* Bottom Buttons */}
                <div className='absolute bottom-0 w-full p-4 border-t border-border/50 bg-[#0d0d14] flex flex-col gap-2'>

                    {/* Take Quiz Button — locked until 100% completion */}
                    {(() => {
                        const completedCount = courseInfo?.courseOutput?.Chapters?.filter((_, idx) => dbChapters.find(c => c.chapterId == String(idx))?.completed).length || 0;
                        const totalCount = courseInfo?.courseOutput?.Chapters?.length || 0;
                        const isFullyCompleted = totalCount > 0 && completedCount === totalCount;

                        return (
                            <button
                                onClick={() => isFullyCompleted && router.push(`/course/${courseId}/quiz`)}
                                disabled={!isFullyCompleted}
                                className={`w-full flex items-center justify-center gap-2 text-sm font-semibold py-3 rounded-xl transition-all duration-300 ${
                                    isFullyCompleted
                                        ? 'bg-[#1DB954] text-black hover:bg-[#1ed760] shadow-lg shadow-[#1DB954]/20 animate-pulse-glow cursor-pointer'
                                        : 'bg-[#282828] text-slate-500 cursor-not-allowed border border-transparent'
                                }`}
                                title={!isFullyCompleted ? 'Complete all chapters to unlock the quiz' : 'Take the course quiz'}
                            >
                                {isFullyCompleted
                                    ? <HiOutlineTrophy className='text-lg' />
                                    : <HiOutlineLockClosed className='text-lg' />
                                }
                                {isFullyCompleted ? 'Take Quiz' : 'Complete all to unlock Quiz'}
                            </button>
                        );
                    })()}

                    <button
                        onClick={downloadCourseAsMarkdown}
                        className='w-full flex items-center justify-center gap-2 bg-[#282828] hover:bg-[#1DB954]/20 hover:text-[#1DB954] hover:border-[#1DB954]/50 border border-transparent text-white text-sm font-semibold py-3 rounded-xl transition-all duration-300'
                    >
                        <HiOutlineDocumentDownload className='text-lg' />
                        Download Course
                    </button>
                </div>
            </div>

            {/* Content */}
            <div className='md:ml-72 w-full'>
                <ChapterContent
                    chapter={selectedChapter}
                    content={chapterContent}
                    isCompleted={dbChapters.find(c => c.chapterId == chapterContent?.chapterId)?.completed}
                    onMarkCompleted={(chapterId, isCompleted) => {
                        setDbChapters(prev => prev.map(c => c.chapterId == chapterId ? { ...c, completed: isCompleted } : c));
                    }}
                />
            </div>
        </div>
    )
}

export default CourseStart;