"use client"
import { getChapterData, getCourseById, getChaptersByCourseId } from '@/configs/action';
import React, { use, useEffect, useState } from 'react'
import ChapterListCard from './_component/ChapterListCard';
import ChapterContent from './_component/ChapterContent';
import { HiOutlineDocumentDownload } from 'react-icons/hi';

function CourseStart({params}) {
    const unwrappedParams = use(params);
    const courseId = unwrappedParams?.courseId;
    
    const [courseInfo, setCourseInfo] = useState(null);
    const [loading, setLoading] = useState(true);
    const [selectedChapter, setSelectedChapter] = useState(null);
    const [chapterContent, setChapterContent] = useState();
    const [dbChapters, setDbChapters] = useState([]);
    
    useEffect(() => {
        const GetCourse = async () => {
            if(!courseId) return;
            setLoading(true);
            try {
                const res = await getCourseById(courseId);
                setCourseInfo(res);
                
                const chaptersRes = await getChaptersByCourseId(courseId);
                setDbChapters(chaptersRes);
                
                if (res?.courseOutput?.Chapters?.length > 0) {
                    setSelectedChapter(res.courseOutput.Chapters[0]);
                    GetSelectedChapterContent(0);
                }
            } catch(error) {
                console.log('Unable to fetch the course: ', error);
            } finally {
                setLoading(false);
            }
        }
    
        GetCourse();
    }, [courseId]);

    const GetSelectedChapterContent = async (index) => {
        try {
            const res = await getChapterData(courseId, index);
            console.log(res);
            setChapterContent(res);
        } catch(error) {
            console.error("Failed to fetch chapter:", error);
        } 
    }

    const downloadCourseAsMarkdown = () => {
        if (!courseInfo) return;

        let markdown = `# ${courseInfo?.courseOutput?.["Course Name"]}\n\n`;
        markdown += `*Generated by Curriculum AI*\n\n---\n\n`;

        courseInfo?.courseOutput?.Chapters?.forEach((chapter, index) => {
            markdown += `## Chapter ${index + 1}: ${chapter?.["Chapter Name"]}\n\n`;
            markdown += `**Duration:** ${chapter?.Duration}\n\n`;
            markdown += `${chapter?.about}\n\n`;

            const dbChapter = dbChapters.find(c => c.chapterId == String(index));
            if (dbChapter?.content?.description) {
                markdown += `### Detailed Explanation\n\n${dbChapter.content.description}\n\n`;
            }

            if (dbChapter?.content?.codeExample && dbChapter.content.codeExample.replace(/<[^>]*>?/gm, '').trim() !== "") {
                markdown += `### Code Example\n\n${dbChapter.content.codeExample}\n\n`;
            }
            markdown += `---\n\n`;
        });

        const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `${courseInfo?.courseOutput?.["Course Name"]?.replace(/\s+/g, '_') || 'Course'}.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

  return (
    <div className='flex min-h-screen bg-background'>
        
        {/* Sidebar */}
        <div className='md:w-72 hidden md:block h-screen fixed border-r border-border/50 bg-[#0d0d14] z-10'>
            <div className='p-4 border-b border-border/50'>
                <h2 className='font-semibold text-sm text-white leading-snug line-clamp-2'>
                    {courseInfo?.courseOutput?.["Course Name"]}
                </h2>
                <div className='flex items-center justify-between mt-3'>
                    <p className='text-xs text-[#B3B3B3]'>
                        {courseInfo?.courseOutput?.Chapters?.filter((_, idx) => dbChapters.find(c => c.chapterId == String(idx))?.completed).length || 0} / {courseInfo?.courseOutput?.Chapters?.length || 0} completed
                    </p>
                    <p className='text-xs font-bold text-[#1DB954]'>
                        {courseInfo?.courseOutput?.Chapters?.length > 0 ? Math.round(((courseInfo?.courseOutput?.Chapters?.filter((_, idx) => dbChapters.find(c => c.chapterId == String(idx))?.completed).length || 0) / courseInfo?.courseOutput?.Chapters?.length) * 100) : 0}%
                    </p>
                </div>
                {/* Progress Bar */}
                <div className="w-full bg-[#282828] rounded-full h-1.5 mt-2 overflow-hidden">
                    <div 
                        className="bg-[#1DB954] h-1.5 transition-all duration-500" 
                        style={{ width: `${courseInfo?.courseOutput?.Chapters?.length > 0 ? ((courseInfo?.courseOutput?.Chapters?.filter((_, idx) => dbChapters.find(c => c.chapterId == String(idx))?.completed).length || 0) / courseInfo?.courseOutput?.Chapters?.length) * 100 : 0}%` }}
                    ></div>
                </div>
            </div>
            <div className='overflow-y-auto h-[calc(100vh-180px)] custom-scrollbar'>
                {courseInfo?.courseOutput?.Chapters.map((chapter, index) => (
                    <div 
                        key={index} 
                        className={`cursor-pointer transition-all duration-200 hover:bg-white/[0.03] ${selectedChapter?.["Chapter Name"] === chapter?.["Chapter Name"] && 'bg-[#1DB954]/10 border-l-2 border-[#1DB954]'}`} 
                        onClick={() => {
                            setSelectedChapter(chapter);
                            GetSelectedChapterContent(index);
                        }}
                    >
                        <ChapterListCard 
                            chapter={chapter} 
                            index={index}
                            isCompleted={dbChapters.find(c => c.chapterId == String(index))?.completed}
                        />
                    </div>
                ))}
            </div>
            
            {/* Download Button */}
            <div className='absolute bottom-0 w-full p-4 border-t border-border/50 bg-[#0d0d14]'>
                <button 
                    onClick={downloadCourseAsMarkdown}
                    className='w-full flex items-center justify-center gap-2 bg-[#282828] hover:bg-[#1DB954]/20 hover:text-[#1DB954] hover:border-[#1DB954]/50 border border-transparent text-white text-sm font-semibold py-3 rounded-xl transition-all duration-300'
                >
                    <HiOutlineDocumentDownload className='text-lg' />
                    Download Course
                </button>
            </div>
        </div>
        
        {/* Content */}
        <div className='md:ml-72 w-full'>
            <ChapterContent 
                chapter={selectedChapter} 
                content={chapterContent}
                isCompleted={dbChapters.find(c => c.chapterId == chapterContent?.chapterId)?.completed}
                onMarkCompleted={(chapterId, isCompleted) => {
                    setDbChapters(prev => prev.map(c => c.chapterId == chapterId ? { ...c, completed: isCompleted } : c));
                }}
            />
        </div>
    </div>
  )
}

export default CourseStart;